Repository SwanseaUniversityMedical/concept-library, pull requests merged in 2024-03, with the labels that each got.

#1577 Changed version for allure pytest as was bug in pytest latest version
  docker/requirements/test-requirements.txt
Labels: Backend, Development

#1578 Update testing-pipline.yml
  .github/workflows/testing-pipline.yml
  docker/requirements/test-requirements.txt
Labels: Automated Functional Test, Tooling

#1592 fix: concept linkage & concept name rendering
  CodeListLibrary_project/clinicalcode/entity_utils/concept_utils.py
  CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
  CodeListLibrary_project/clinicalcode/urls.py
  CodeListLibrary_project/clinicalcode/views/adminTemp.py
  CodeListLibrary_project/cll/static/js/clinicalcode/forms/clinical/conceptCreator.js
  CodeListLibrary_project/cll/static/scss/_utils.scss
  CodeListLibrary_project/cll/static/scss/pages/create.scss
  CodeListLibrary_project/cll/templates/components/create/inputs/clinical/concept.html
  CodeListLibrary_project/cll/templates/components/details/outputs/phenotype_clinical_code_lists.html
  docs/sql-scripts/examine_concepts.sql
Labels: Data issue, Backend, Development

#1594 Ontology detail & Reference data views
  CodeListLibrary_project/clinicalcode/entity_utils/constants.py
  CodeListLibrary_project/clinicalcode/models/OntologyTag.py
  CodeListLibrary_project/clinicalcode/templatetags/detail_pg_renderer.py
  CodeListLibrary_project/clinicalcode/views/View.py
  CodeListLibrary_project/cll/static/js/clinicalcode/services/referenceDataService.js
  CodeListLibrary_project/cll/static/scss/_variables.scss
  CodeListLibrary_project/cll/static/scss/components/_chips.scss
  CodeListLibrary_project/cll/static/scss/components/_inputs.scss
  CodeListLibrary_project/cll/static/scss/components/_misc.scss
  CodeListLibrary_project/cll/static/scss/pages/create.scss
  CodeListLibrary_project/cll/static/scss/pages/detail.scss
  CodeListLibrary_project/cll/templates/clinicalcode/about/reference_data.html
  CodeListLibrary_project/cll/templates/components/details/outputs/dropdown.html
  CodeListLibrary_project/cll/templates/components/details/outputs/generic/ontology.html
  CodeListLibrary_project/cll/templates/components/details/outputs/id.html
  CodeListLibrary_project/cll/templates/components/details/outputs/tagbox.html
  CodeListLibrary_project/dynamic_templates/atlas_phecode.json
Labels: Frontend, Backend, Development

#1601 fix: vary render status of components and/or data as described by template properties
  CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
  CodeListLibrary_project/clinicalcode/models/Template.py
  CodeListLibrary_project/clinicalcode/views/View.py
  CodeListLibrary_project/cll/templates/clinicalcode/about/reference_data.html
Labels: Backend, Development
