Repository SwanseaUniversityMedical/concept-library, pull requests merged in 2024-07, with the labels that each got.

#1689 Invalid date fix for the moderation page
  CodeListLibrary_project/cll/static/js/clinicalcode/services/collectionService.js
Labels: Frontend

#1660 test: add functional & unit test cases
  CodeListLibrary_project/clinicalcode/entity_utils/email_utils.py
  CodeListLibrary_project/clinicalcode/templatetags/entity_publish_renderer.py
  CodeListLibrary_project/clinicalcode/tests/conftest.py
  CodeListLibrary_project/clinicalcode/tests/functional_tests/test_collection_components.py
  CodeListLibrary_project/clinicalcode/tests/functional_tests/test_detail_components.py
  CodeListLibrary_project/clinicalcode/tests/functional_tests/test_moderation_components.py
  CodeListLibrary_project/clinicalcode/tests/unit_tests/test_publishing.py
  CodeListLibrary_project/cll/static/js/clinicalcode/forms/entityPublish.js
  CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/detail/detail_buttons.html
  CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/publish/publish.html
  CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/publish/request_publish.html
  CodeListLibrary_project/cll/templates/components/publish_request/publish_button.html
  CodeListLibrary_project/cll/templates/components/search/search_banner.html
  CodeListLibrary_project/pytest.ini
Labels: Unit Test, Automated Functional Test

#1700 Update templates, FE and adminTemp for phenoflow changes
  CodeListLibrary_project/clinicalcode/entity_utils/entity_db_utils.py
  CodeListLibrary_project/clinicalcode/urls.py
  CodeListLibrary_project/clinicalcode/views/adminTemp.py
  CodeListLibrary_project/cll/templates/clinicalcode/adminTemp/admin_temp_tool.html
  CodeListLibrary_project/cll/templates/components/details/outputs/phenoflowid.html
  CodeListLibrary_project/dynamic_templates/clinical_coded_phenotype.json
  CodeListLibrary_project/dynamic_templates/structured_data_algorithm_phenotype.json
Labels: Development

#1695 fix!: safer data implementation & fix deprecated SCSS unquote usage
  CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py
  CodeListLibrary_project/cll/static/js/clinicalcode/components/entitySelector.js
  CodeListLibrary_project/cll/static/js/clinicalcode/components/fuzzyQuery.js
  CodeListLibrary_project/cll/static/js/clinicalcode/components/modal.js
  CodeListLibrary_project/cll/static/js/clinicalcode/components/tagify.js
  CodeListLibrary_project/cll/static/js/clinicalcode/components/toastNotification.js
  CodeListLibrary_project/cll/static/js/clinicalcode/components/tooltipFactory.js
  CodeListLibrary_project/cll/static/js/clinicalcode/components/virtualisedList/virtualList.js
  CodeListLibrary_project/cll/static/js/clinicalcode/forms/clinical/publicationCreator.js
  CodeListLibrary_project/cll/static/js/clinicalcode/forms/entityCreator/utils.js
  CodeListLibrary_project/cll/static/js/clinicalcode/forms/stringInputListCreator.js
  CodeListLibrary_project/cll/static/js/clinicalcode/services/collectionService.js
  CodeListLibrary_project/cll/static/js/clinicalcode/services/referenceDataService.js
  CodeListLibrary_project/cll/static/js/clinicalcode/utils.js
  CodeListLibrary_project/cll/static/scss/_methods.scss
  CodeListLibrary_project/cll/templates/clinicalcode/about/reference_data.html
  CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/create.html
  CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/select.html
  CodeListLibrary_project/cll/templates/clinicalcode/moderation/index.html
  CodeListLibrary_project/cll/templates/clinicalcode/profile/my_collection.html
  CodeListLibrary_project/cll/templates/components/create/inputs/clinical/concept.html
  CodeListLibrary_project/cll/templates/components/create/inputs/clinical/publication.html
  CodeListLibrary_project/cll/templates/components/create/inputs/generic/ontology.html
  CodeListLibrary_project/cll/templates/components/create/inputs/grouped_enum.html
  CodeListLibrary_project/cll/templates/components/create/inputs/markdown.html
  CodeListLibrary_project/cll/templates/components/create/inputs/string_inputlist.html
  CodeListLibrary_project/cll/templates/components/create/inputs/tagbox.html
Labels: Enhancement, Frontend, Development
